# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/sysadminsmedia/homebox:0.17.2"
  amd64: "ghcr.io/sysadminsmedia/homebox:0.17.2"
  armv7: "ghcr.io/sysadminsmedia/homebox:0.17.2"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Homebox"
  org.opencontainers.image.description: "Installs homebox under hassio"
  org.opencontainers.image.source: "https://github.com/sysadminsmedia/homebox-ha-addon"
  org.opencontainers.image.licenses: ""
args:
  TEMPIO_VERSION: "2021.09.0"
