# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/sysadminsmedia/homebox:0.17.2"
  amd64: "ghcr.io/sysadminsmedia/homebox:0.17.2"
  armv7: "ghcr.io/sysadminsmedia/homebox:0.17.2"
