# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Homebox Addon
version: "0.17.2"
slug: homebox
description: Homebox add-on for Home Assistant
url: "https://github.com/sysadminsmedia/homebox-ha-addon/"
arch:
  # - armhf
  - armv7
  - aarch64
  - amd64
  # - i386
map:
  - share:rw
init: false
#ingess_entry: "/local_homebox/ingress"
ingress_port: 8099
hassio_api: true
#auth_api: true
environment:
  HBOX_OPTIONS_CHECK_GITHUB_RELEASE: "false"

#webui: "http://[HOST]:[PORT:7745]/"
ingress: true
#image: "ghcr.io/gcraig99/homebox-ha-addon"
ports:
  7745/tcp: 7745
